### ISSUE TITLE
Null-Safety Support!

### ISSUE THREAD

**Issue by tomassasovsky** [malihanan/draw_graph#2]
This package should be migrated to Null-Safety. You can use this [migration guide](https://dart.dev/null-safety/migration-guide).

**Comment by malihanan** [comment]
Thanks for pointing it out @tomassasovsky 
This commit - https://github.com/malihanan/draw_graph/commit/9bbda9234bfedad8490cee8f9ed0475da2dd5296 migrates the package to Null-Safety.
Closing this issue.
